version: "3.4"

services:
  # web-react:
  #   build:
  #     context: .
  #     dockerfile: ./config/dockerfiles/Dockerfile-node
  #     args:
  #       APP_PATH: ./services/web-react
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./services/web-react:/app
  #   command:
  #     - ./docker-compose-start.sh
  #   depends_on:
  #     - api-rails
  #   stdin_open: true
  #   tty: true
  api-dictionary:
    build:
      context: .
      dockerfile: ./config/dockerfiles/Dockerfile-ruby
      args:
        APP_PATH: ./services/api-dictionary
    ports:
      - '3001:3000'
    env_file:
      - ./config/environments/.development.env
    volumes:
      - ./services/api-dictionary:/app
    depends_on:
      - db-mysql
    command:
      - ./docker-compose-start.sh
    stdin_open: true
    tty: true
  #   to run with byebug:
  #   docker-compose up -d && docker attach groundzero_api-rails_1
  db-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 4500:3306
    logging:
      driver: "none"
    environment:
      MYSQL_ROOT_PASSWORD: rails
      MYSQL_USERNAME: rails
      MYSQL_PASSWORD: rails
  db-admin:
    image: adminer
    restart: always
    ports:
      - 3005:8080
    logging:
      driver: "none"
    depends_on:
      - db-mysql
volumes:
  db_data:
